plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.wificonstraineduploader'
version = '0.1.0'

android {
  namespace "expo.modules.wificonstraineduploader"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.work:work-runtime-ktx:2.10.0"
  implementation "com.squareup.okhttp3:okhttp:4.12.0"
}
